name = "Yusuf"
number = 12
[[theme]]
from = 30
to = 31
text = "Yusuf dipenjara"

[[theme]]
from = 1
to = 52
text = "Kisah Nabi Yusuf A.S"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 101
to = 101
text = "Doa mohon diwafatkan sebagai muslim"

