name = "Al-Kahf"
number = 18
[[theme]]
from = 1
to = 9
text = "Al-Qur'an sebagai bimbingan yang lurus"

[[theme]]
from = 10
to = 10
text = "Doa dimudahkan segala urusan"

[[theme]]
from = 11
to = 22
text = "Ancaman terhadap kepercayaan Tuhan punya anak"

[[theme]]
from = 23
to = 24
text = "Etika dalam berjanji"

[[theme]]
from = 27
to = 31
text = "Larangan pilih kasih dalam mengajak kepada kebenaran"

[[theme]]
from = 39
to = 39
text = "Tiada kekuatan selain dari pertolongan Allah"

[[theme]]
from = 46
to = 46
text = "Kebaikan yang terus menerus lebih baik daripada harta & anak"

[[theme]]
from = 60
to = 82
text = "Kisah Nabi Musa AS Mencari Ilmu. Nabi Musa AS bertemu dengan Khidr AS"

[[theme]]
from = 102
to = 106
text = "Celakalah orang-orang musyrik & Amat merugilah orang-orang yang terpedaya oleh dirinya sendiri"

[[theme]]
from = 107
to = 110
text = "Surga firdaus bagi orang yang beramal saleh dan luasnya ilmu Allah tidak terhingga"

