name = "Al-Ahzab"
number = 33
[[theme]]
from = 1
to = 10
text = "Bantuan Allah kepada kaum muslimin dalam peperangan Ahzab"

[[theme]]
from = 11
to = 21
text = "Bantuan Allah kepada kaum muslimin dalam peperangan Ahzab"

[[theme]]
from = 22
to = 44
text = "Sifat-sifat orang mu'min dan kewajiban mereka terhadap perintah rasul"

[[theme]]
from = 45
to = 58
text = "Adab dan sopan santun dalam rumah tangga Nabi S.A.W."

[[theme]]
from = 59
to = 59
text = "Menutup aurat / Hijab"

[[theme]]
from = 60
to = 63
text = "Ancaman-ancaman terhadap orang-orang munafik dan orang-orang yang membuat kerusuhan di Madinah"

