name = "At-Taghabun"
number = 64
[[theme]]
from = 1
to = 10
text = "Kesalahan-kesalahan manusia akan dinampakkan Allah pada hari kiamat"

[[theme]]
from = 11
to = 13
text = "Kesalahan-kesalahan manusia akan dinampakkan pada hari kiamat"

[[theme]]
from = 14
to = 18
text = "QS 65 At-Talaq: 1-12"

