name = "At-Tahriim"
number = 66
[[theme]]
from = 1
to = 5
text = "Beberapa tuntunan tentang kehidupan rumah tangga"

[[theme]]
from = 6
to = 9
text = "Perintah memelihara diri dan keluarga dari adzab Allah & perintah taubat dan berjihad"

[[theme]]
from = 10
to = 12
text = "Contoh-contoh tentang isteri yang tidak baik dan isteri yang baik"

