name = "Al-Insaan"
number = 76
[[theme]]
from = 1
to = 11
text = "Kehidupan manusia menuju kesempurnaan"

[[theme]]
from = 12
to = 22
text = "Kesempurnaan hidup di dalam surga"

[[theme]]
from = 23
to = 31
text = "Tuntunan-tuntunan Allah kepada Muhammad SAW"

