name = "Yunus"
number = 10
[[topic]]
from = 1
to = 10
text = "Tanda-tanda kebesaran Allah dalam alam semesta"

[[topic]]
from = 25
to = 30
text = "Ajakan masuk surga"

[[topic]]
from = 40
to = 56
text = "Bukti-bukti kekuasaan Allah yang membatalkan kepercayaan orang"

[[topic]]
from = 57
to = 57
text = "Al-Qur'an sebagai penyembuh & petunjuk"

