name = "Huud"
number = 11
[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 6
to = 6
text = "Rezeki semua makhluk sudah dijamin Allah"

[[topic]]
from = 47
to = 49
text = "Keselamatan seseorang tergantung amalnya"

[[topic]]
from = 114
to = 115
text = "Perbuatan baik menghapus kesalahan"

