name = "Ibrahim"
number = 14
[[theme]]
from = 1
to = 3
text = "Al-Qur'an menunjuki semua umat manusia ke jalan yang terang"

[[theme]]
from = 4
to = 7
text = "Jika bersyukur akan ditambah nikmatnya"

[[theme]]
from = 8
to = 18
text = "Sikap umat manusia menghadapi ajaran Rasul"

[[theme]]
from = 19
to = 23
text = "Akibat yang diderita oleh kaum yang menolak kebenaran"

[[theme]]
from = 24
to = 27
text = "Perumpamaan kalimat yang baik seperti pohon yang baik"

[[theme]]
from = 28
to = 39
text = "Tindakan-tindakan pemimpin yang menyebabkan kehancuran pengikut-pengikutnya"

[[theme]]
from = 40
to = 40
text = "Doa agar anak tetap sholat"

[[theme]]
from = 41
to = 41
text = "Doa agar orangtua diampuni"

[[theme]]
from = 42
to = 45
text = "Orang yang zalim pasti dapat azab"

[[theme]]
from = 46
to = 51
text = "kosong"

[[theme]]
from = 52
to = 52
text = "Al-Qur'an adalah penjelasan yang sempurna"

