name = "Al-Israa"
number = 17
[[theme]]
from = 1
to = 15
text = "Isyarat kepada umat islam sebagai suatu umat yang akan menjadi besar"

[[theme]]
from = 23
to = 24
text = "Adab & doa kepada orangtua"

[[theme]]
from = 25
to = 28
text = "Beberapa tata krama pergaulan"

[[theme]]
from = 29
to = 29
text = "Jangan terlalu pelit & jangan terlalu pemurah"

[[theme]]
from = 30
to = 32
text = "Beberapa tata krama pergaulan"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 78
to = 79
text = "Perintah tahajjud & sholat 5 waktu"

