name = "Tohaa"
number = 20
[[topic]]
from = 1
to = 24
text = "Perintah Allah kepada Nabi Musa A.S. dan permohonan Nabi Musa A.S."

[[topic]]
from = 25
to = 28
text = "Doa mempermudah urusan"

[[topic]]
from = 29
to = 41
text = "Ni'mat-ni'mat Allah kepada Nabi Musa A.S. sejak kecil"

[[topic]]
from = 112
to = 114
text = "Hak orang beriman dan diturunkannya Al Qur'an dengan bahasa Arab"

[[topic]]
from = 132
to = 135
text = "kewajiban suami mengajak keluarganya sholat"

