name = "Al-Anbiyaa"
number = 21
[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 83
to = 84
text = "Doa ketika ditimpa penyakit"

[[theme]]
from = 0
to = 0
text = "kosong"

[[theme]]
from = 21
to = 25
text = "kosong"

