name = "Al-Hajj"
number = 22
[[topic]]
from = 11
to = 13
text = "Celaan terhadap orang-orang yang tidak berpendirian"

[[topic]]
from = 15
to = 17
text = "Pertolongan Allah pasti datang"

[[topic]]
from = 18
to = 18
text = "Semua bersujud kepada Allah"

[[topic]]
from = 26
to = 28
text = "Haji, Menasiknya, & Syi'arnya"

[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 58
to = 62
text = "Balasan terhadap orang-orang yang mati dalam berhijrah di jalan Allah"

