name = "Al-Qasas"
number = 28
[[topic]]
from = 26
to = 26
text = "kosong"

[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 77
to = 77
text = "Mengejar akhirat tidak boleh meninggalkan dunia"

[[topic]]
from = 88
to = 88
text = "Segalanya akan binasa kecuali Allah"

