name = "Ali-Imran"
number = 3
[[theme]]
from = 1
to = 4
text = "Al-Qur'an & kitab-kitab sebelumnya"

[[theme]]
from = 5
to = 7
text = "Al-Qur'an dan kitab-kitab yang sebelumnya"

[[theme]]
from = 8
to = 9
text = "Doa petunjuk hati"

[[theme]]
from = 10
to = 13
text = "Ancaman Allah kepada orang-orang kafir dan pengaruh harta benda duniawi"

[[theme]]
from = 14
to = 14
text = "Kesenangan hidup di dunia"

[[theme]]
from = 15
to = 17
text = "Doa minta ampun dari dosa"

[[theme]]
from = 18
to = 27
text = "Pernyataan Allah tentang keesaan dan keadilan-Nya serta agama yang di ridhai-Nya"

[[theme]]
from = 28
to = 32
text = "Larangan berpihak kepada orang kafir"

[[theme]]
from = 33
to = 37
text = "Keutamaan keluarga 'Imran"

[[theme]]
from = 38
to = 50
text = "Keutamaan keluarga 'Imran"

[[theme]]
from = 38
to = 50
text = "Keutamaan keluarga 'Imran"

[[theme]]
from = 51
to = 52
text = "Nabi Isa & sahabatnya adalah penolong agama Allah"

[[theme]]
from = 53
to = 65
text = "Ajakan kepada agama Tauhid \"Millatu Ibrahim\""

[[theme]]
from = 66
to = 75
text = "QS 3 Ali-Imran: 76-77"

[[theme]]
from = 78
to = 103
text = "Bantahan Allah terhadap pendapat-pendapat ahli kitab yang keliru"

[[theme]]
from = 104
to = 104
text = "Keharusan menjaga persatuan"

[[theme]]
from = 105
to = 127
text = "kelebihan umat islam dari umat yang lain"

[[theme]]
from = 128
to = 129
text = "Sabar dan tawakal kepada Allah pangkal kemenangan"

[[theme]]
from = 130
to = 135
text = "Larangan memakan riba & ciri orang bertakwa"

[[theme]]
from = 136
to = 144
text = "Agama Nabi Ibrahim A.S"

[[theme]]
from = 145
to = 145
text = "Balasan dunia akhirat"

[[theme]]
from = 146
to = 151
text = "Kehidupan dunia adalah kesenangan yang memperdaya"

[[theme]]
from = 152
to = 161
text = "kosong"

[[theme]]
from = 162
to = 184
text = "kosong"

[[theme]]
from = 185
to = 186
text = "Kehidupan dunia adalah kesenangan yang memperdaya"

[[theme]]
from = 187
to = 191
text = "Kebakhilan dan dusta serta balasannya"

[[theme]]
from = 192
to = 194
text = "Doa orang beriman & jawaban Allah"

[[theme]]
from = 195
to = 195
text = "Faedah selalu ingat kepada Allah dan merenungkan ciptaan-Nya"

[[theme]]
from = 196
to = 199
text = "Kesenangan sementara bagi orang-orang kafir dan kebahagiaan abadi bagi orang mu'min"

