name = "As-Sajdah"
number = 32
[[topic]]
from = 1
to = 11
text = "Al-Qur'an bukanlah ciptaan Muhammad S.A.W"

[[topic]]
from = 12
to = 15
text = "Sebuah perbandingan antara orang mu'min dengan orang kafir"

[[topic]]
from = 16
to = 22
text = "Sebuah perbandingan antara orang mu'min dengan orang kafir"

[[topic]]
from = 23
to = 30
text = "Jangan ragu dalam menerima Al-Qur'an"

