name = "Fatir"
number = 35
[[topic]]
from = 1
to = 7
text = "Allah adalah Pencipta, Penguasa, dan Pemberi rahmat"

[[topic]]
from = 29
to = 29
text = "Balasan kepada orang yang membaca Al-Qur'an, mendirikan sholat & sedekah"

[[topic]]
from = 0
to = 0
text = "kosong"

