name = "Ash-Shaaffaat"
number = 37
[[topic]]
from = 1
to = 70
text = "Bukti-bukti keesaan Allah. Alam langit dipelihara dari gangguan syaitan"

[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 100
to = 101
text = "Doa memohon anak yang soleh"

[[topic]]
from = 0
to = 0
text = "kosong"

