name = "Az-Zumar"
number = 39
[[theme]]
from = 1
to = 5
text = "Beribadah kepada Allah dengan hati yang penuh keikhlasan"

[[theme]]
from = 10
to = 18
text = "Beribadah kepada Allah dengan hati yang penuh keikhlasan"

[[theme]]
from = 53
to = 55
text = "Allah mengampuni semua dosa"

