name = "Fussilat"
number = 41
[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 30
to = 35
text = "Sifat baik dianugerahkan kepada orang yang sabar"

[[topic]]
from = 0
to = 0
text = "kosong"

