name = "Asy-Syuraa"
number = 42
[[topic]]
from = 1
to = 12
text = "Perselisihan-perselisihan umat manusia dikembalikan penyelesainnya kepada Kitab Allah"

[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 30
to = 43
text = "Bersabar & Memaafkan"

[[topic]]
from = 0
to = 0
text = "kosong"

