name = "Al-Ahqaaf"
number = 46
[[topic]]
from = 1
to = 14
text = "Kebenaran tauhid dan kebatilan syirik"

[[topic]]
from = 15
to = 15
text = "Doa mohon dapat bersyukur"

[[topic]]
from = 16
to = 35
text = "Kebenaran tauhid dan kebatilan syirik"

