name = "Muhammad"
number = 47
[[theme]]
from = 1
to = 6
text = "Sikap menghadapi orang-orang kafir dalam peperangan"

[[theme]]
from = 7
to = 9
text = "Sikap menghadapi orang-orang kafir dalam peperangan"

[[theme]]
from = 10
to = 38
text = "Ancaman terhadp orang-orang munafik dan orang-orang murtad"

