name = "Al-Hujuraat"
number = 49
[[theme]]
from = 1
to = 5
text = "Tatakrama terhadap Rasulullah S.A.W"

[[theme]]
from = 6
to = 6
text = "Perintah memastikan kebenaran sebuah berita"

[[theme]]
from = 7
to = 9
text = "Tatakrama terhadap Rasulullah S.A.W"

[[theme]]
from = 10
to = 12
text = "Orang muslim itu bersaudara & Jangan merendahkan orang lain / berprasangka"

[[theme]]
from = 13
to = 13
text = "Manusia diciptakan berbeda untuk saling mengenal"

[[theme]]
from = 14
to = 18
text = "Ciri-ciri iman yang sebenarnya"

