name = "Al-Maidah"
number = 5
[[topic]]
from = 6
to = 6
text = "Perintah untuk wudhu & membersihkan badan"

[[topic]]
from = 8
to = 8
text = "Kewajiban berlaku Adil dan Jujur"

[[topic]]
from = 9
to = 31
text = "kosong"

[[topic]]
from = 32
to = 40
text = "Hukum terhadap perusuh dan pengacau keamanan"

[[topic]]
from = 51
to = 53
text = "Dilarang berteman akrab dengan orang-orang Yahudi dan Nasrani dan akibat melanggarnya"

[[topic]]
from = 89
to = 93
text = "Larangan meminum khamar, berjudi, berkorban untuk berhala dan mengundi nasib"

