name = "Qaaf"
number = 50
[[topic]]
from = 1
to = 15
text = "Hari Berbangkit"

[[topic]]
from = 16
to = 16
text = "Allah itu dekat"

[[topic]]
from = 17
to = 26
text = "Kejadian-kejadian dalam alam membuktikan kebenaran adanya hari berbangkit"

[[topic]]
from = 0
to = 0
text = "kosong"

