name = "Ath-Thuur"
number = 52
[[topic]]
from = 1
to = 20
text = "Bukit"

[[topic]]
from = 21
to = 21
text = "Allah mempertemukan keluarga yang beriman dengan anak cucu mereka di dalam surga"

[[topic]]
from = 22
to = 49
text = "Bukit"

