name = "Al-An'am"
number = 6
[[topic]]
from = 1
to = 20
text = "Keagungan Allah dan persaksian-Nya atas kenabian Muhammad S.A.W."

[[topic]]
from = 32
to = 32
text = "Perbedaan dunia & akhirat"

[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 53
to = 58
text = "Tuntunan-tuntunan dalam menghadapi masyarakat"

[[topic]]
from = 0
to = 0
text = "kosong"

[[topic]]
from = 106
to = 108
text = "Saling menghormati dalam beragama"

[[topic]]
from = 141
to = 143
text = "Besarnya Karunia Allah kepada Manusia"

[[topic]]
from = 159
to = 161
text = "Peraturan-peraturan yang dibuat-buat oleh kaum musyrikin dan pimpinan Allah terhadap kaum muslimin"

