name = "Al-Munafiquun"
number = 63
[[topic]]
from = 1
to = 8
text = "Sifat-sifat orang munafik"

[[topic]]
from = 9
to = 9
text = "Janganlah harta & anak melalaikan dari mengingat Allah"

[[topic]]
from = 10
to = 11
text = "Sifat-sifat orang munafik"

