name = "Al-Anfaal"
number = 8
[[topic]]
from = 2
to = 4
text = "Sifat-sifat orang mukmin"

[[topic]]
from = 5
to = 19
text = "kosong"

[[topic]]
from = 5
to = 19
text = "Keengganan sebahagian sahabat untuk pergi ke peperangan badar dan pertolongan Allah kepada kaum musl"

[[topic]]
from = 20
to = 30
text = "Larangan menyalahi perintah-perintah Allah"

[[topic]]
from = 0
to = 0
text = "kosong"

